export const currencies = [
  { "name": "United Arab Emirates Dirham", "symbol": "د.إ.", "code": "AED" },
  { "name": "Afghan Afghani", "symbol": "؋", "code": "AFN" },
  { "name": "Albanian Lek", "symbol": "Lek", "code": "ALL" },
  { "name": "Armenian Dram", "symbol": "֏", "code": "AMD" },
  { "name": "Netherlands Antillean Guilder", "symbol": "ƒ", "code": "ANG" },
  { "name": "Angolan Kwanza", "symbol": "Kz", "code": "AOA" },
  { "name": "Argentine Peso", "symbol": "AR$", "code": "ARS" },
  { "name": "Australian Dollar", "symbol": "AU$", "code": "AUD" },
  { "name": "Aruban Florin", "symbol": "ƒ", "code": "AWG" },
  { "name": "Azerbaijani Manat", "symbol": "ман", "code": "AZN" },
  { "name": "Bosnia-Herzegovina Convertible Mark", "symbol": "KM", "code": "BAM" },
  { "name": "Bangladeshi Taka", "symbol": "Tk", "code": "BDT" },
  { "name": "Bulgarian Lev", "symbol": "лв", "code": "BGN" },
  { "name": "Bahraini Dinar", "symbol": ".د.ب", "code": "BHD" },
  { "name": "Burundian Franc", "symbol": "FBu", "code": "BIF" },
  { "name": "Bermudan Dollar", "symbol": "$", "code": "BMD" },
  { "name": "Brunei Dollar", "symbol": "B$", "code": "BND" },
  { "name": "Bolivian Boliviano", "symbol": "Bs.", "code": "BOB" },
  { "name": "Brazilian Real", "symbol": "R$", "code": "BRL" },
  { "name": "Bahamian Dollar", "symbol": "B$", "code": "BSD" },
  { "name": "Bhutanese Ngultrum", "symbol": "Nu.", "code": "BTN" },
  { "name": "Botswanan Pula", "symbol": "P", "code": "BWP" },
  { "name": "Belarusian Ruble", "symbol": "Br", "code": "BYN" },
  { "name": "Belize Dollar", "symbol": "BZ$", "code": "BZD" },
  { "name": "Canadian Dollar", "symbol": "CA$", "code": "CAD" },
  { "name": "Congolese Franc", "symbol": "FC", "code": "CDF" },
  { "name": "Swiss Franc", "symbol": "CHF", "code": "CHF" },
  { "name": "Chilean Peso", "symbol": "CL$", "code": "CLP" },
  { "name": "Chinese Yuan", "symbol": "¥", "code": "CNY" },
  { "name": "Colombian Peso", "symbol": "CO$", "code": "COP" },
  { "name": "Costa Rican Colón", "symbol": "₡", "code": "CRC" },
  { "name": "Cuban Convertible Peso", "symbol": "CUC$", "code": "CUC" },
  { "name": "Cuban Peso", "symbol": "₱", "code": "CUP" },
  { "name": "Cape Verdean Escudo", "symbol": "Esc", "code": "CVE" },
  { "name": "Czech Republic Koruna", "symbol": "Kč", "code": "CZK" },
  { "name": "Djiboutian Franc", "symbol": "Fdj", "code": "DJF" },
  { "name": "Danish Krone", "symbol": "kr", "code": "DKK" },
  { "name": "Dominican Peso", "symbol": "RD$", "code": "DOP" },
  { "name": "Algerian Dinar", "symbol": "د.ج", "code": "DZD" },
  { "name": "Egyptian Pound", "symbol": "E£", "code": "EGP" },
  { "name": "Eritrean Nakfa", "symbol": "Nfk", "code": "ERN" },
  { "name": "Ethiopian Birr", "symbol": "Br", "code": "ETB" },
  { "name": "Euro", "symbol": "€", "code": "EUR" },
  { "name": "Fijian Dollar", "symbol": "FJ$", "code": "FJD" },
  { "name": "Falkland Islands Pound", "symbol": "£", "code": "FKP" },
  { "name": "British Pound Sterling", "symbol": "£", "code": "GBP" },
  { "name": "Georgian Lari", "symbol": " GEL", "code": "GEL" },
  { "name": "Ghanaian Cedi", "symbol": "GH¢", "code": "GHS" },
  { "name": "Gibraltar Pound", "symbol": "£", "code": "GIP" },
  { "name": "Gambian Dalasi", "symbol": "D", "code": "GMD" },
  { "name": "Guinean Franc", "symbol": "FG", "code": "GNF" },
  { "name": "Guatemalan Quetzal", "symbol": "Q", "code": "GTQ" },
  { "name": "Guyanaese Dollar", "symbol": "GY$", "code": "GYD" },
  { "name": "Hong Kong Dollar", "symbol": "HK$", "code": "HKD" },
  { "name": "Honduran Lempira", "symbol": "L", "code": "HNL" },
  { "name": "Croatian Kuna", "symbol": "kn", "code": "HRK" },
  { "name": "Haitian Gourde", "symbol": "G", "code": "HTG" },
  { "name": "Hungarian Forint", "symbol": "Ft", "code": "HUF" },
  { "name": "Indonesian Rupiah", "symbol": "Rp", "code": "IDR" },
  { "name": "Israeli New Sheqel", "symbol": "₪", "code": "ILS" },
  { "name": "Indian Rupee", "symbol": "₹", "code": "INR" },
  { "name": "Iraqi Dinar", "symbol": "ع.د", "code": "IQD" },
  { "name": "Iranian Rial", "symbol": "﷼", "code": "IRR" },
  { "name": "Icelandic Króna", "symbol": "kr", "code": "ISK" },
  { "name": "Jamaican Dollar", "symbol": "J$", "code": "JMD" },
  { "name": "Jordanian Dinar", "symbol": "د.ا", "code": "JOD" },
  { "name": "Japanese Yen", "symbol": "¥", "code": "JPY" },
  { "name": "Kenyan Shilling", "symbol": "KSh", "code": "KES" },
  { "name": "Kyrgystani Som", "symbol": "с", "code": "KGS" },
  { "name": "Cambodian Riel", "symbol": "៛", "code": "KHR" },
  { "name": "Comorian Franc", "symbol": "CF", "code": "KMF" },
  { "name": "South Korean Won", "symbol": "₩", "code": "KRW" },
  { "name": "Kuwaiti Dinar", "symbol": "د.ك", "code": "KWD" },
  { "name": "Cayman Islands Dollar", "symbol": "CI$", "code": "KYD" },
  { "name": "Kazakhstani Tenge", "symbol": "₸", "code": "KZT" },
  { "name": "Laotian Kip", "symbol": "₭", "code": "LAK" },
  { "name": "Lebanese Pound", "symbol": "ل.ل", "code": "LBP" },
  { "name": "Sri Lankan Rupee", "symbol": "Rs.", "code": "LKR" },
  { "name": "Liberian Dollar", "symbol": "L$", "code": "LRD" },
  { "name": "Lesotho Loti", "symbol": "L", "code": "LSL" },
  { "name": "Libyan Dinar", "symbol": "ل.د", "code": "LYD" },
  { "name": "Moroccan Dirham", "symbol": "د.م.", "code": "MAD" },
  { "name": "Moldovan Leu", "symbol": "L", "code": "MDL" },
  { "name": "Malagasy Ariary", "symbol": "Ar", "code": "MGA" },
  { "name": "Macedonian Denar", "symbol": "ден", "code": "MKD" },
  { "name": "Myanma Kyat", "symbol": "Ks", "code": "MMK" },
  { "name": "Mongolian Tugrik", "symbol": "₮", "code": "MNT" },
  { "name": "Macanese Pataca", "symbol": "P", "code": "MOP" },
  { "name": "Mauritanian Ouguiya", "symbol": "UM", "code": "MRU" },
  { "name": "Mauritian Rupee", "symbol": "Rs", "code": "MUR" },
  { "name": "Maldivian Rufiyaa", "symbol": "Rf", "code": "MVR" },
  { "name": "Malawian Kwacha", "symbol": "MK", "code": "MWK" },
  { "name": "Mexican Peso", "symbol": "Mex$", "code": "MXN" },
  { "name": "Malaysian Ringgit", "symbol": "RM", "code": "MYR" },
  { "name": "Mozambican Metical", "symbol": "MT", "code": "MZN" },
  { "name": "Namibian Dollar", "symbol": "N$", "code": "NAD" },
  { "name": "Nigerian Naira", "symbol": "₦", "code": "NGN" },
  { "name": "Nicaraguan Córdoba", "symbol": "C$", "code": "NIO" },
  { "name": "Norwegian Krone", "symbol": "kr", "code": "NOK" },
  { "name": "Nepalese Rupee", "symbol": "रू", "code": "NPR" },
  { "name": "New Zealand Dollar", "symbol": "NZ$", "code": "NZD" },
  { "name": "Omani Rial", "symbol": "ر.ع.", "code": "OMR" },
  { "name": "Panamanian Balboa", "symbol": "B/.", "code": "PAB" },
  { "name": "Peruvian Sol", "symbol": "S/.", "code": "PEN" },
  { "name": "Papua New Guinean Kina", "symbol": "K", "code": "PGK" },
  { "name": "Philippine Peso", "symbol": "₱", "code": "PHP" },
  { "name": "Pakistani Rupee", "symbol": "₨", "code": "PKR" },
  { "name": "Polish Zloty", "symbol": "zł", "code": "PLN" },
  { "name": "Paraguayan Guarani", "symbol": "₲", "code": "PYG" },
  { "name": "Qatari Rial", "symbol": "ر.ق", "code": "QAR" },
  { "name": "Romanian Leu", "symbol": "L", "code": "RON" },
  { "name": "Serbian Dinar", "symbol": "дин", "code": "RSD" },
  { "name": "Russian Ruble", "symbol": "₽", "code": "RUB" },
  { "name": "Rwandan Franc", "symbol": "FRw", "code": "RWF" },
  { "name": "Saudi Riyal", "symbol": "ر.س", "code": "SAR" },
  { "name": "Solomon Islands Dollar", "symbol": "SI$", "code": "SBD" },
  { "name": "Seychellois Rupee", "symbol": "₨", "code": "SCR" },
  { "name": "Sudanese Pound", "symbol": "ج.س.", "code": "SDG" },
  { "name": "Swedish Krona", "symbol": "kr", "code": "SEK" },
  { "name": "Singapore Dollar", "symbol": "S$", "code": "SGD" },
  { "name": "Saint Helena Pound", "symbol": "£", "code": "SHP" },
  { "name": "Sierra Leonean Leone", "symbol": "Le", "code": "SLL" },
  { "name": "Somali Shilling", "symbol": "Sh", "code": "SOS" },
  { "name": "Surinamese Dollar", "symbol": "$", "code": "SRD" },
  { "name": "South Sudanese Pound", "symbol": "£", "code": "SSP" },
  { "name": "São Tomé and Príncipe Dobra", "symbol": "Db", "code": "STD" },
  { "name": "Syrian Pound", "symbol": "£", "code": "SYP" },
  { "name": "Swazi Lilangeni", "symbol": "L", "code": "SZL" },
  { "name": "Thai Baht", "symbol": "฿", "code": "THB" },
  { "name": "Tajikistani Somoni", "symbol": "ЅМ", "code": "TJS" },
  { "name": "Turkmenistani Manat", "symbol": "m", "code": "TMT" },
  { "name": "Tunisian Dinar", "symbol": "د.ت", "code": "TND" },
  { "name": "Tongan Paʻanga", "symbol": "T$", "code": "TOP" },
  { "name": "Turkish Lira", "symbol": "₺", "code": "TRY" },
  { "name": "Trinidad and Tobago Dollar", "symbol": "TT$", "code": "TTD" },
  { "name": "New Taiwan Dollar", "symbol": "NT$", "code": "TWD" },
  { "name": "Tanzanian Shilling", "symbol": "Sh", "code": "TZS" },
  { "name": "Ukrainian Hryvnia", "symbol": "₴", "code": "UAH" },
  { "name": "Ugandan Shilling", "symbol": "USh", "code": "UGX" },
  { "name": "United States Dollar", "symbol": "$", "code": "USD" },
  { "name": "Uruguayan Peso", "symbol": "$U", "code": "UYU" },
  { "name": "Uzbekistan Som", "symbol": "сум", "code": "UZS" },
  { "name": "Venezuelan Bolívar Soberano", "symbol": "Bs.S", "code": "VES" },
  { "name": "Vietnamese Đồng", "symbol": "₫", "code": "VND" },
  { "name": "Vanuatu Vatu", "symbol": "Vt", "code": "VUV" },
  { "name": "Samoan Tala", "symbol": "WS$", "code": "WST" },
  { "name": "Central African CFA Franc", "symbol": "FCFA", "code": "XAF" },
  { "name": "East Caribbean Dollar", "symbol": "EC$", "code": "XCD" },
  { "name": "West African CFA Franc", "symbol": "CFA", "code": "XOF" },
  { "name": "CFP Franc", "symbol": "₣", "code": "XPF" },
  { "name": "Yemeni Rial", "symbol": "﷼", "code": "YER" },
  { "name": "South African Rand", "symbol": "R", "code": "ZAR" },
  { "name": "Zambian Kwacha", "symbol": "ZK", "code": "ZMW" }
]
